global:
  scrape_interval:     15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: server-metrics
    scrape_interval: 5s
    static_configs:
      - targets: ['host.docker.internal:9111', 'host.docker.internal:9112', 'host.docker.internal:9113']