dial-grpc-timeout: 10

order:
  service-name: order
  service-protocol: http
  http-addr: 127.0.0.1:8282
  grpc-addr: 127.0.0.1:8182

stock:
  service-name: stock
  service-protocol: grpc
  http-addr: 127.0.0.1:8283
  grpc-addr: 127.0.0.1:8183

payment:
  service-name: payment
  service-protocol: http
  http-addr: 127.0.0.1:8284
  grpc-addr: 127.0.0.1:8184

consul:
  address: 127.0.0.1:8500

rabbitmq:
  user: guest
  password: guest
  host: 127.0.0.1
  port: 5672

stripe-key: "${STRIPE_KEY}" # 值仅为提示作用，viper 会直接寻找 STRIPE_KEY 环境变量
stripe-endpoint-secret: "${STRIPE_ENDPOINT_SECRET}"