dial-grpc-timeout: 10

order:
  service-name: order
  service-protocol: http
  http-addr: 127.0.0.1:8282
  grpc-addr: 127.0.0.1:8182

stock:
  service-name: stock
  service-protocol: grpc
  http-addr: 127.0.0.1:8283
  grpc-addr: 127.0.0.1:8183

payment:
  service-name: payment
  service-protocol: http
  http-addr: 127.0.0.1:8284
  grpc-addr: 127.0.0.1:8184

consul:
  address: 127.0.0.1:8500

jaeger:
  url: http://127.0.0.1:14268/api/traces

rabbitmq:
  user: guest
  password: guest
  host: 127.0.0.1
  port: 5672
  max-retry: 3

mongo:
  user: root
  password: password
  host: 127.0.0.1
  port: 27017
  db-name: order
  coll-name: order

mysql:
  user: root
  password: root
  host: 127.0.0.1
  port: 3307
  dbname: "gorder_v2"

redis:
  local:
    ip: 127.0.0.1
    port: 6379
    pool_size: 100
    max_conn: 100
    conn_timeout: 1000
    read_timeout: 1000
    write_timeout: 1000

stripe-key: "${STRIPE_KEY}" # 值仅为提示作用，viper 会直接寻找 STRIPE_KEY 环境变量
stripe-endpoint-secret: "${STRIPE_ENDPOINT_SECRET}"